sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    password: 123456

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tEurNXahGwZQ2bPZVcr
    access-key-secret: hJvHWX6O6YFi5lvag8YcCKMPM68fFq
    bucket-name: cangqip-sky

  wechat:
    appid: wx77e3e9b5d2d30681
    secret: db0bb93cc5c77d7bef2c46eb7ed657cc
    #以下是微信支付的商户信息
    #商户号（微信支付申请获取）
    mchid: 0
    #商户序列号
    mch-serial-no: 0
    #商户私钥
    api-v3-key: 0
    #下两条为微信认证后下载后的认证文件路径
    we-chat-pay-cert-file-path: 0
    private-key-file-path: 0
    # 微信支付后回调商户的路径
    notify-url: 0
    # 回调退款的路径
    refund-notify-url: 0
